version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped