services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    environment:
      VITE_API_BASE: http://localhost:8000
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: wfhubby
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wfhubby123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
